language: cpp

git:
  depth: 10

notifications:
  email: false

addons:
  apt:
    packages:
      - libssl-dev
      - python-dev
      - scons
      - swig

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
    - os: osx
      compiler: clang

before_install:
- |
  if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    brew install openssl scons swig
  fi

script:
- scons
- sudo scons install
- python test.py

# TODO: run the unit tests

