language: cpp

git:
  depth: 10

notifications:
  email: false

addons:
  apt:
    packages:
      - libssl-dev
      - python-dev
      - scons
      - swig

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
    - os: osx
      compiler: clang

before_install:
- |
  if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    brew install openssl scons swig
  fi
  python -V

# Travis supplies their own version of Python, and advise not to use the
# system Python environment.

script:
- python `which scons`
- sudo python `which scons` install
- python test.py || python -v -c 'import s2' && exit 1

# TODO: run the unit tests

